// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNfuLUthCKPLd9UCDWjxLnQaNj4fpKLXU',
    appId: '1:234433931029:web:92abe2d45731f9ba696b1c',
    messagingSenderId: '234433931029',
    projectId: 'corvitweekendeve',
    authDomain: 'corvitweekendeve.firebaseapp.com',
    databaseURL: 'https://corvitweekendeve-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvitweekendeve.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVqvSvIMUR2lMYpPd1l5KL-_Hb2S8fciI',
    appId: '1:234433931029:android:2244f59e83ed1d9b696b1c',
    messagingSenderId: '234433931029',
    projectId: 'corvitweekendeve',
    databaseURL: 'https://corvitweekendeve-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvitweekendeve.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe8O1bZ_Mdt-ISW01oTtW5EdUtlOT0h08',
    appId: '1:234433931029:ios:adcae500b0b18e68696b1c',
    messagingSenderId: '234433931029',
    projectId: 'corvitweekendeve',
    databaseURL: 'https://corvitweekendeve-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvitweekendeve.appspot.com',
    iosBundleId: 'com.proglabs.corvit.corvitWeekendEve',
  );
}
